{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "e4d5248f",
   "metadata": {},
   "outputs": [],
   "source": [
    "#1)Explain why we have to use the Exception class while creating a Custom Exception.\n",
    "\n",
    "''' \n",
    "When creating custom exceptions in a programming language, it is a good \n",
    "practice to inherit from the base Exception class provided by the language. \n",
    "Here are a few reasons why using the Exception class is beneficial when creating\n",
    "custom exceptions:\n",
    "\n",
    "Standardization: The Exception class is a standardized base class provided by \n",
    "the language. By inheriting from it, you follow established conventions and make\n",
    "your custom exception consistent with other exceptions in the language. This \n",
    "makes your code more maintainable and easier for other developers to understand.\n",
    "\n",
    "Error Handling: The Exception class provides a rich set of methods and properties\n",
    "that facilitate error handling. It includes methods like getMessage() or \n",
    "toString() that allow you to retrieve detailed information about the exception. \n",
    "By inheriting from Exception, your custom exception automatically inherits these\n",
    "helpful methods, making it easier to handle and log exceptions consistently \n",
    "across your codebase.\n",
    "\n",
    "Compatibility: Most programming languages provide built-in mechanisms for \n",
    "catching and handling exceptions. These mechanisms typically expect exceptions \n",
    "to be instances of the base Exception class or its derivatives. By using the \n",
    "Exception class as the base for your custom exception, you ensure compatibility \n",
    "with existing exception handling mechanisms and libraries.\n",
    "\n",
    "Exception Hierarchy: In many programming languages, exceptions are organized \n",
    "into a hierarchy, with more specific exception classes inheriting from more \n",
    "general ones. By inheriting from Exception, you can position your custom \n",
    "exception in the appropriate place within this hierarchy, making it easier for \n",
    "developers to catch and handle specific types of exceptions.\n",
    "\n",
    "Exception Filtering: In some situations, you may want to catch and handle only \n",
    "specific types of exceptions. By using the Exception class as the base for your \n",
    "custom exception, you enable the ability to catch and filter exceptions based \n",
    "on their type. This allows for more fine-grained exception handling and helps \n",
    "differentiate between different types of errors.\n",
    "\n",
    "Overall, using the Exception class as the base for custom exceptions provides \n",
    "consistency, compatibility, and standardization in error handling. It ensures \n",
    "that your custom exceptions work seamlessly with existing exception handling \n",
    "mechanisms and allows for more effective and organized exception handling in \n",
    "your code.\n",
    "\n",
    "\n",
    "\n",
    "'''"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "ae97db2d",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Exception\n",
      "    TypeError\n",
      "        FloatOperation\n",
      "        MultipartConversionError\n",
      "    StopAsyncIteration\n",
      "    StopIteration\n",
      "    ImportError\n",
      "        ModuleNotFoundError\n",
      "        ZipImportError\n",
      "    OSError\n",
      "        ConnectionError\n",
      "            BrokenPipeError\n",
      "            ConnectionAbortedError\n",
      "            ConnectionRefusedError\n",
      "            ConnectionResetError\n",
      "                RemoteDisconnected\n",
      "        BlockingIOError\n",
      "        ChildProcessError\n",
      "        FileExistsError\n",
      "        FileNotFoundError\n",
      "        IsADirectoryError\n",
      "        NotADirectoryError\n",
      "        InterruptedError\n",
      "            InterruptedSystemCall\n",
      "        PermissionError\n",
      "        ProcessLookupError\n",
      "        TimeoutError\n",
      "        UnsupportedOperation\n",
      "        herror\n",
      "        gaierror\n",
      "        timeout\n",
      "        SSLError\n",
      "            SSLCertVerificationError\n",
      "            SSLZeroReturnError\n",
      "            SSLWantReadError\n",
      "            SSLWantWriteError\n",
      "            SSLSyscallError\n",
      "            SSLEOFError\n",
      "        Error\n",
      "            SameFileError\n",
      "        SpecialFileError\n",
      "        ExecError\n",
      "        ReadError\n",
      "        URLError\n",
      "            HTTPError\n",
      "            ContentTooShortError\n",
      "        BadGzipFile\n",
      "    EOFError\n",
      "        IncompleteReadError\n",
      "    RuntimeError\n",
      "        RecursionError\n",
      "        NotImplementedError\n",
      "            ZMQVersionError\n",
      "            StdinNotImplementedError\n",
      "        _DeadlockError\n",
      "        BrokenBarrierError\n",
      "        BrokenExecutor\n",
      "            BrokenThreadPool\n",
      "        SendfileNotAvailableError\n",
      "        ExtractionError\n",
      "        VariableError\n",
      "    NameError\n",
      "        UnboundLocalError\n",
      "    AttributeError\n",
      "        FrozenInstanceError\n",
      "    SyntaxError\n",
      "        IndentationError\n",
      "            TabError\n",
      "    LookupError\n",
      "        IndexError\n",
      "        KeyError\n",
      "            NoSuchKernel\n",
      "            UnknownBackend\n",
      "        CodecRegistryError\n",
      "    ValueError\n",
      "        UnicodeError\n",
      "            UnicodeEncodeError\n",
      "            UnicodeDecodeError\n",
      "            UnicodeTranslateError\n",
      "        UnsupportedOperation\n",
      "        JSONDecodeError\n",
      "        SSLCertVerificationError\n",
      "        Error\n",
      "        IllegalMonthError\n",
      "        IllegalWeekdayError\n",
      "        ParserError\n",
      "        ClassNotFound\n",
      "        ClipboardEmpty\n",
      "        MessageDefect\n",
      "            NoBoundaryInMultipartDefect\n",
      "            StartBoundaryNotFoundDefect\n",
      "            CloseBoundaryNotFoundDefect\n",
      "            FirstHeaderLineIsContinuationDefect\n",
      "            MisplacedEnvelopeHeaderDefect\n",
      "            MissingHeaderBodySeparatorDefect\n",
      "            MultipartInvariantViolationDefect\n",
      "            InvalidMultipartContentTransferEncodingDefect\n",
      "            UndecodableBytesDefect\n",
      "            InvalidBase64PaddingDefect\n",
      "            InvalidBase64CharactersDefect\n",
      "            InvalidBase64LengthDefect\n",
      "            HeaderDefect\n",
      "                InvalidHeaderDefect\n",
      "                HeaderMissingRequiredValue\n",
      "                NonPrintableDefect\n",
      "                ObsoleteHeaderDefect\n",
      "                NonASCIILocalPartDefect\n",
      "        MacroToEdit\n",
      "        InvalidFileException\n",
      "        UnequalIterablesError\n",
      "        InvalidVersion\n",
      "        _InvalidELFFileHeader\n",
      "        InvalidWheelFilename\n",
      "        InvalidSdistFilename\n",
      "        InvalidSpecifier\n",
      "        InvalidMarker\n",
      "        UndefinedComparison\n",
      "        UndefinedEnvironmentName\n",
      "        InvalidRequirement\n",
      "            RequirementParseError\n",
      "        InvalidVersion\n",
      "    AssertionError\n",
      "    ArithmeticError\n",
      "        FloatingPointError\n",
      "        OverflowError\n",
      "        ZeroDivisionError\n",
      "            DivisionByZero\n",
      "            DivisionUndefined\n",
      "        DecimalException\n",
      "            Clamped\n",
      "            Rounded\n",
      "                Underflow\n",
      "                Overflow\n",
      "            Inexact\n",
      "                Underflow\n",
      "                Overflow\n",
      "            Subnormal\n",
      "                Underflow\n",
      "            DivisionByZero\n",
      "            FloatOperation\n",
      "            InvalidOperation\n",
      "                ConversionSyntax\n",
      "                DivisionImpossible\n",
      "                DivisionUndefined\n",
      "                InvalidContext\n",
      "    SystemError\n",
      "        CodecRegistryError\n",
      "    ReferenceError\n",
      "    MemoryError\n",
      "    BufferError\n",
      "    Warning\n",
      "        UserWarning\n",
      "            GetPassWarning\n",
      "            FormatterWarning\n",
      "        DeprecationWarning\n",
      "            ProvisionalWarning\n",
      "        PendingDeprecationWarning\n",
      "        SyntaxWarning\n",
      "        RuntimeWarning\n",
      "            ProactorSelectorThreadWarning\n",
      "            UnknownTimezoneWarning\n",
      "            PEP440Warning\n",
      "        FutureWarning\n",
      "            ProvisionalCompleterWarning\n",
      "        ImportWarning\n",
      "        UnicodeWarning\n",
      "        BytesWarning\n",
      "        ResourceWarning\n",
      "        DeprecatedTzFormatWarning\n",
      "        PkgResourcesDeprecationWarning\n",
      "    Error\n",
      "    _OptionError\n",
      "    error\n",
      "    Verbose\n",
      "    _Error\n",
      "    SubprocessError\n",
      "        CalledProcessError\n",
      "        TimeoutExpired\n",
      "    TokenError\n",
      "    StopTokenizing\n",
      "    ClassFoundException\n",
      "    EndOfBlock\n",
      "    TraitError\n",
      "    Error\n",
      "    Error\n",
      "        CancelledError\n",
      "        TimeoutError\n",
      "        InvalidStateError\n",
      "    _GiveupOnSendfile\n",
      "    error\n",
      "    Incomplete\n",
      "    TimeoutError\n",
      "    InvalidStateError\n",
      "    LimitOverrunError\n",
      "    QueueEmpty\n",
      "    QueueFull\n",
      "    error\n",
      "    LZMAError\n",
      "    RegistryError\n",
      "    _GiveupOnFastCopy\n",
      "    Empty\n",
      "    Full\n",
      "    ZMQBaseError\n",
      "        ZMQError\n",
      "            ContextTerminated\n",
      "            Again\n",
      "            InterruptedSystemCall\n",
      "        ZMQBindError\n",
      "        NotDone\n",
      "    PickleError\n",
      "        PicklingError\n",
      "        UnpicklingError\n",
      "    _Stop\n",
      "    ArgumentError\n",
      "    ArgumentTypeError\n",
      "    ConfigError\n",
      "        ConfigLoaderError\n",
      "            ArgumentError\n",
      "        ConfigFileNotFound\n",
      "    ConfigurableError\n",
      "        MultipleInstanceError\n",
      "    ApplicationError\n",
      "    TimeoutError\n",
      "    COMError\n",
      "    ArgumentError\n",
      "    ReturnValueIgnoredError\n",
      "    KeyReuseError\n",
      "    UnknownKeyError\n",
      "    LeakedCallbackError\n",
      "    BadYieldError\n",
      "    ReturnValueIgnoredError\n",
      "    Return\n",
      "    InvalidPortNumber\n",
      "    NoIPAddresses\n",
      "    BadZipFile\n",
      "    LargeZipFile\n",
      "    Error\n",
      "        NoSectionError\n",
      "        DuplicateSectionError\n",
      "        DuplicateOptionError\n",
      "        NoOptionError\n",
      "        InterpolationError\n",
      "            InterpolationMissingOptionError\n",
      "            InterpolationSyntaxError\n",
      "            InterpolationDepthError\n",
      "        ParsingError\n",
      "            MissingSectionHeaderError\n",
      "    BadEntryPoint\n",
      "    NoSuchEntryPoint\n",
      "    DuplicateKernelError\n",
      "    ErrorDuringImport\n",
      "    BdbQuit\n",
      "    Restart\n",
      "    FindCmdError\n",
      "    HomeDirError\n",
      "    ProfileDirError\n",
      "    IPythonCoreError\n",
      "        TryNext\n",
      "        UsageError\n",
      "        StdinNotImplementedError\n",
      "    InputRejected\n",
      "    GetoptError\n",
      "    OptionError\n",
      "    ErrorToken\n",
      "    PrefilterError\n",
      "    AliasError\n",
      "        InvalidAliasError\n",
      "    Error\n",
      "        InterfaceError\n",
      "        DatabaseError\n",
      "            InternalError\n",
      "            OperationalError\n",
      "            ProgrammingError\n",
      "            IntegrityError\n",
      "            DataError\n",
      "            NotSupportedError\n",
      "    Warning\n",
      "    SpaceInInput\n",
      "    DOMException\n",
      "        IndexSizeErr\n",
      "        DomstringSizeErr\n",
      "        HierarchyRequestErr\n",
      "        WrongDocumentErr\n",
      "        InvalidCharacterErr\n",
      "        NoDataAllowedErr\n",
      "        NoModificationAllowedErr\n",
      "        NotFoundErr\n",
      "        NotSupportedErr\n",
      "        InuseAttributeErr\n",
      "        InvalidStateErr\n",
      "        SyntaxErr\n",
      "        InvalidModificationErr\n",
      "        NamespaceErr\n",
      "        InvalidAccessErr\n",
      "        ValidationErr\n",
      "    ValidationError\n",
      "    EditReadOnlyBuffer\n",
      "    _Retry\n",
      "    InvalidLayoutError\n",
      "    HeightIsUnknownError\n",
      "    ParserSyntaxError\n",
      "    InternalParseError\n",
      "    _PositionUpdatingFinished\n",
      "    SimpleGetItemNotFound\n",
      "    UncaughtAttributeError\n",
      "    HasNoContext\n",
      "    ParamIssue\n",
      "    _JediError\n",
      "        InternalError\n",
      "        WrongVersion\n",
      "        RefactoringError\n",
      "    OnErrorLeaf\n",
      "    InvalidPythonEnvironment\n",
      "    MessageError\n",
      "        MessageParseError\n",
      "            HeaderParseError\n",
      "            BoundaryError\n",
      "        MultipartConversionError\n",
      "        CharsetError\n",
      "    Error\n",
      "    HTTPException\n",
      "        NotConnected\n",
      "        InvalidURL\n",
      "        UnknownProtocol\n",
      "        UnknownTransferEncoding\n",
      "        UnimplementedFileMode\n",
      "        IncompleteRead\n",
      "        ImproperConnectionState\n",
      "            CannotSendRequest\n",
      "            CannotSendHeader\n",
      "            ResponseNotReady\n",
      "        BadStatusLine\n",
      "            RemoteDisconnected\n",
      "        LineTooLong\n",
      "    InteractivelyDefined\n",
      "    KillEmbedded\n",
      "    Error\n",
      "        NoSuchProcess\n",
      "            ZombieProcess\n",
      "        AccessDenied\n",
      "        TimeoutExpired\n",
      "    Error\n",
      "    TimeoutExpired\n",
      "    TimeoutAbandoned\n",
      "    QueueEmpty\n",
      "    QueueFull\n",
      "    ExpatError\n",
      "    Error\n",
      "        ProtocolError\n",
      "        ResponseError\n",
      "        Fault\n",
      "    error\n",
      "    com_error\n",
      "    internal_error\n",
      "    ParseBaseException\n",
      "        ParseException\n",
      "        ParseFatalException\n",
      "            ParseSyntaxException\n",
      "    RecursiveGrammarException\n",
      "    ResolutionError\n",
      "        VersionConflict\n",
      "            ContextualVersionConflict\n",
      "        DistributionNotFound\n",
      "        UnknownExtra\n",
      "    UnableToResolveVariableException\n",
      "    InvalidTypeInArgsException\n"
     ]
    }
   ],
   "source": [
    "#Q2. Write a python program to print Python Exception Hierarchy.\n",
    "def print_exception_hierarchy(exception_class, indent=0):\n",
    "    print(' ' * indent + exception_class.__name__)\n",
    "    for subclass in exception_class.__subclasses__():\n",
    "        print_exception_hierarchy(subclass, indent + 4)\n",
    "\n",
    "# Start from the base Exception class\n",
    "print_exception_hierarchy(Exception)\n",
    "\n",
    "#When you run this program, it will recursively print the exception hierarchy, \n",
    "#starting from the Exception class. Each exception class will be indented by \n",
    "#four spaces to represent its position within the hierarchy.\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "4c28e7d1",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error: Division by zero occurred.\n"
     ]
    }
   ],
   "source": [
    "#Q3. What errors are defined in the ArithmeticError class? Explain any two with \n",
    "#an example.\n",
    "\n",
    "#The ArithmeticError class in Python is a base class for exceptions that occur \n",
    "#during arithmetic operations. It provides a common ancestor for more specific \n",
    "#arithmetic-related exception classes.\n",
    "\n",
    "#1) ZeroDivisionError: This exception is raised when attempting to divide a \n",
    "#number by zero.\n",
    "try:\n",
    "    result = 10 / 0\n",
    "except ZeroDivisionError:\n",
    "    print(\"Error: Division by zero occurred.\")\n",
    "    \n",
    "# the code tries to perform a division operation by dividing 10 by 0. Since \n",
    "#division by zero is undefined in mathematics, it raises a ZeroDivisionError. \n",
    "#The except block catches the exception and prints an error message.\n",
    "\n",
    "#2) OverflowError: This exception is raised when a calculation exceeds the \n",
    "#maximum representable value for a numeric type.\n",
    "\n",
    "import sys\n",
    "\n",
    "try:\n",
    "    result = sys.maxsize + 1\n",
    "except OverflowError:\n",
    "    print(\"Error: Integer overflow occurred.\")\n",
    "\n",
    "#the code tries to add 1 to the maximum representable integer value \n",
    "#(sys.maxsize). Since the result exceeds the range that can be stored in an \n",
    "#integer, it raises an OverflowError. The except block catches the exception and\n",
    "#prints an error message."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "fd3fe71f",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error: Key not found in the dictionary.\n",
      "Error: Index out of range.\n",
      " \n"
     ]
    }
   ],
   "source": [
    "#Q4. Why LookupError class is used? Explain with an example KeyError and \n",
    "#IndexError.\n",
    "\n",
    "'''\n",
    "The LookupError class in Python is a base class for exceptions that occur \n",
    "when a key or index is not found during a lookup operation. It provides a \n",
    "common ancestor for more specific lookup-related exception classes. \n",
    "Two examples of exceptions that are defined within the LookupError class are \n",
    "KeyError and IndexError.\n",
    "\n",
    "1) KeyError: This exception is raised when a dictionary key is not found.\n",
    "'''\n",
    "my_dict = {'a': 1, 'b': 2, 'c': 3}\n",
    "\n",
    "try:\n",
    "    value = my_dict['d']\n",
    "except KeyError:\n",
    "    print(\"Error: Key not found in the dictionary.\")\n",
    "\n",
    "'''\n",
    "here the code tries to access the value associated with the key 'd' in the \n",
    "my_dict dictionary. However, since the key 'd' does not exist in the dictionary,\n",
    "a KeyError is raised. The except block catches the exception and prints an error\n",
    "message.\n",
    "\n",
    "2) IndexError: This exception is raised when a sequence index is out of range.\n",
    "'''\n",
    "my_list = [1, 2, 3]\n",
    "\n",
    "try:\n",
    "    value = my_list[5]\n",
    "except IndexError:\n",
    "    print(\"Error: Index out of range.\")\n",
    "\n",
    "'''\n",
    " the code tries to access the value at index 5 in the my_list list. However, \n",
    " since the list has only three elements, and indexing starts from zero, \n",
    " accessing index 5 is out of range. As a result, an IndexError is raised. \n",
    " The except block catches the exception and prints an error message.\n",
    "\n",
    "These examples demonstrate how the LookupError class and its subclasses, such \n",
    "as KeyError and IndexError, can be used to handle lookup-related errors. By \n",
    "catching these exceptions, you can handle situations where a specific key or \n",
    "index is not found and provide appropriate error messages or alternative \n",
    "behavior in your code\n",
    "'''\n",
    "print(\" \")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "6dae5cc4",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error: Failed to import the module.\n",
      "Error: The module could not be found.\n",
      " \n"
     ]
    }
   ],
   "source": [
    "#Q5. Explain ImportError. What is ModuleNotFoundError?\n",
    "\n",
    "'''\n",
    "In Python, ImportError is an exception that is raised when an import statement \n",
    "fails to find or load a module. It is a subclass of the Exception class and is \n",
    "commonly used to handle errors related to module imports.\n",
    "\n",
    "When an ImportError occurs, it typically means that the Python interpreter was \n",
    "unable to locate the module you were trying to import. This can happen for \n",
    "various reasons, such as the module not being installed or not being in the \n",
    "search path.\n",
    "'''\n",
    "try:\n",
    "    import non_existent_module\n",
    "except ImportError:\n",
    "    print(\"Error: Failed to import the module.\")\n",
    "\n",
    "    \n",
    "'''\n",
    "In this example, the code tries to import a module named non_existent_module, \n",
    "which does not exist. As a result, an ImportError is raised. The except block \n",
    "catches the exception and prints an error message.\n",
    "\n",
    "On the other hand, ModuleNotFoundError is a subclass of ImportError that \n",
    "specifically indicates that a module could not be found. It was introduced in \n",
    "Python 3.6 to provide a more specific error message when a module is not found \n",
    "during import.\n",
    "'''\n",
    "try:\n",
    "    import non_existent_module\n",
    "except ModuleNotFoundError:\n",
    "    print(\"Error: The module could not be found.\")\n",
    "\n",
    "'''\n",
    " this example, the code attempts to import the same non-existent module as \n",
    " before. However, the except block now catches the more specific \n",
    " ModuleNotFoundError instead of the general ImportError.\n",
    " '''\n",
    "print(\" \")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "97ac408a",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      " I am trying to handle a ZeroDivision error\n"
     ]
    }
   ],
   "source": [
    "#Q6. List down some best practices for exception handling in python.\n",
    "# print always a proper message\n",
    "try:\n",
    "    10/0\n",
    "except ZeroDivisionError as e:\n",
    "    print(\" I am trying to handle a ZeroDivision error\")\n",
    "    \n",
    "# always try to log a error\n",
    "import logging\n",
    "\n",
    "logging.basicConfig(filename =\"error.log\",level = logging.ERROR)\n",
    "try :\n",
    "    10/0\n",
    "except ZeroDivisionError as e:\n",
    "    logging.error(\"I am trying to handle a ZeroDivision error {}\".format(e))\n",
    "    \n",
    "    \n",
    "#always avoid towrite a multiple exception handling\n",
    "try:\n",
    "    10/0\n",
    "except FileNotFoundError:\n",
    "      logging.error(\"I am handling  a file not found error {}\".format(e))\n",
    "except AttributeError as e:\n",
    "    logging.error(\"I am handling Attribute error {}\".format(e))\n",
    "except ZeroDivisionError as e:\n",
    "    logging.error(\"I am trying to handle a ZeroDivision error {}\".format(e))\n",
    "    \n",
    "# document all the error\n",
    "# clean up all the resources\n",
    "try:\n",
    "    with open(\"test.txt\",\"w\") as f:\n",
    "        f.write(\"this is my data to file.\")\n",
    "except FileNotFoundError as e:\n",
    "    logging.error(\"I handling file not found {}\".format(e))\n",
    "finally:\n",
    "    f.close()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "acceee1f",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.13"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
